export const FlocThemeLight = {
    colors: {
        primaryBgColor: "#f6f6f6",
        whiteBgColor: "#ffffff",
        primaryColor: "#fcf328",
        hintTextColor: "#4d745e",
        placeholderColor: "#9c9c9c",
        inputTextColor: "#262626",
        inputErrorColor: "#e03f3f",
        buttonErrorColor: "#e03f3f",
        tertiaryTextColor: "#e03f3f",
        disabledColor: "#c1c1c1",
        primaryTextColor: "#4a4a4a",
        secondaryTextColor: "#262626",
        descriptionColor: "#8b8b8b",
        priceColor: "#6cc350",
        avatarBackgroundColor: "#dedbdb",
        onlineColor: "#7bd75e",
        bannerStepperColor: "#595959",
        whiteTextColor: "#ffffff",
        productDetailBgColor: "#99e382",
        cartActionsColor: "#a1c57b",
        sliderBgColor: "#ffffff",
        sliderActiveColor: "#b8eda7",
        sliderHeartColor: "#7bd75e",
        lineColor: "#d7f3ce",
        borderColor: "#e3e3e3",
        favoriteHeartColor: "#e03f3f",
        freeDeliveryBgColor: "#6cc350",
        freeDeliveryNoBgColor: "#529f3a",
        newProductBgColor: "#5555ff",
        seePixColor: "#5555ff",
        trendingProductBgColor: "#f50e02",
        errorColor: "#f50e02",
        promotionProductBgColor: "#457204",
        loadingColor: "#F5E01E",
        blackTextColor: "#000000",
    },
    fontSizes: {
        presentationText: 1.2,
        inputText: 1,
        inputError: 0.9,
        inputLabel: 0.8,
    },
    sizes: {
        borderRadius: 12,
        iconProfileMenu: 20,
        iconListDefault: 24,
        iconListSmall: 16,
        iconArrowDefault: 18,
        iconDefault: 18,
        iconCancel: 24,
        radiusFullyRound: 30,
        backButtonSize: 32,
        unknownArrowSize: 38,
    },
};
